#!/usr/bin/env bash
# Script that creates the file /var/run/myscript.pid containing its PID

echo "$$" > /var/run/myscript.pid

delete_func()
{
	rm /var/run/myscript.pid
	exit
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && delete_func' SIGTERM
  trap 'delete_func' SIGQUIT
done
