#!/usr/bin/env bash
# Script that parses Apache log files in list format.
# groups visitors by IP and HTTP status code.
# displays the number of occurrences, IP, and HTTP status
# code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
